"""
Source used as a guide for this file: "Python: Creating a HASHMAP using Lists" by Joe James (https://youtu.be/9HFbhPscPU0)
"""


# "get_hash" function to generate the identifier hash for each entry in the hash table
def get_hash(key):
    return key % 10  # The hash for the package will be the value of the last digit, which will cause 4 collisions per bucket


# "HashTable" class to contain the self-adjusting data structure (hash table) that will be used to store all the package data
class HashTable:
    # constructor function for the Hash Table
    def __init__(self):
        self.size = 10  # the hash table array will have a size of 10 buckets, each holding 4 values
        self.map = [None] * self.size  # initialize the buckets in the hash table array to be filled in later

    # "insert" function to insert new entries into the hash table
    def insert(self, key, value):
        key_hash = get_hash(key)  # call the "get_hash" function to get the key hash of the package
        key_value = [key, value]  # the actual value that will be inserted into the array bucket(s)

        if self.map[key_hash] is None:  # if the selected bucket is empty...
            self.map[key_hash] = list([key_value])  # ...add a list containing the new value to the selected bucket
            return True  # exit the function
        else:  # if the selected bucket is not empty...
            for pair in self.map[key_hash]:  # ...for each key-value pair contained in the selected bucket
                if pair[0] == key:  # if the pair's key matches the hash generated by the new package...
                    pair[1] = value  # ...update the pair's value to match the new package's value
                    return True  # exit the function
            self.map[key_hash].append(
                key_value)  # if none of the existing keys match the new package's hash, append the new package to the bucket
            return True  # exit the function

    # "get" function to acquire entries from the hash table
    def get(self, key):
        key_hash = get_hash(key)  # generate the hash from the input key
        if self.map[key_hash] is not None:  # if the bucket matching the key hash is not empty...
            for pair in self.map[key_hash]:  # ...for each key-value pair contained in the selected bucket
                if pair[0] == key:  # if the pair's key matches the hash generated by the input key...
                    return pair[1]  # ...return the pair's value
        return None  # if the bucket matching the key hash is empty, return None

    # "remove" function to remove entries in the hash table
    def remove(self, key):
        key_hash = get_hash(key)  # generate the hash from the input key
        if self.map[key_hash] is None:  # if the bucket matching the key hash is empty...
            return False  # exit the function without doing anything
        # if the bucket is not empty...
        for i in range(0, len(self.map[key_hash])):  # for every value in the bucket...
            if self.map[key_hash][i][0] == key:  # if the individual key in the bucket matches the input key...
                self.map[key_hash].pop(i)  # ..."pop" the individual value off of the hash table
                return True  # exit the function
        return None  # if none of the above, exit the function without doing anything

    # "print" function to print out all the data in the hash table (not used)
    def print(self):
        print('---PACKAGES---')  # a simple header for the console
        for item in self.map:  # for each bucket in the table
            if item is not None:  # if the bucket is not empty...
                print(str(item))  # ... print the bucket to the console

    # "__str__" function to allow easy printing of the hash table's contents for easy testing and debugging (not used)
    def __str__(self):
        return str(self.map)

    # "__repr__" function to allow easy printing of the hash table's contents for easy testing and debugging (not used)
    def __repr__(self):
        return self.__str__()
